// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package main

import (
	"fmt"

	"github.com/JorMath/mc-tui-server/internal/server"
	tui "github.com/grindlemire/go-tui"
)

type HintsRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *HintsRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *HintsRowView) GetRoot() *tui.Element { return v.Root }

func (v *HintsRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *HintsRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *HintsRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *HintsRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*HintsRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*HintsRowView)(nil)

var _ tui.AppUnbinder = (*HintsRowView)(nil)

var _ tui.PropsUpdater = (*HintsRowView)(nil)

func HintsRow(hints []hint, green bool) *HintsRowView {
	var view HintsRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexWrap(tui.Wrap),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	for i, h := range hints {
		_ = i
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		if i > 0 {
			__tui_2 := tui.New(
				tui.WithText("|"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_1.AddChild(__tui_2)
		}
		if green {
			__tui_3 := tui.New(
				tui.WithText(h.K),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
			)
			__tui_1.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(h.K),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_1.AddChild(__tui_4)
		}
		__tui_5 := tui.New(
			tui.WithText(h.L),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_5)
		__tui_0.AddChild(__tui_1)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = HintsRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SidebarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SidebarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SidebarView) GetRoot() *tui.Element { return v.Root }

func (v *SidebarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SidebarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SidebarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SidebarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SidebarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SidebarView)(nil)

var _ tui.AppUnbinder = (*SidebarView)(nil)

var _ tui.PropsUpdater = (*SidebarView)(nil)

func Sidebar(a *app) *SidebarView {
	var view SidebarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithFlexShrink(0),
		tui.WithMinWidth(a.sidebarMinWidth()),
	)
	__tui_1 := tui.New(
		tui.WithText("Instances"),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	if len(a.managers.Get()) == 0 {
		__tui_2 := tui.New(
			tui.WithText("No instances yet."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("Press n to create one"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	}
	for i, mgr := range a.managers.Get() {
		_ = i
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		if i == a.selected.Get() {
			__tui_6 := tui.New(
				tui.WithText(fmt.Sprintf("> %s%s", mgr.Instance().Name, autoMark(a.autoRestartOn(mgr.Instance().Name)))),
				tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
			)
			__tui_5.AddChild(__tui_6)
		} else {
			__tui_7 := tui.New(
				tui.WithText(fmt.Sprintf("  %s%s", mgr.Instance().Name, autoMark(a.autoRestartOn(mgr.Instance().Name)))),
			)
			__tui_5.AddChild(__tui_7)
		}
		if a.statusText(mgr.Instance().Name) == string(server.Running) {
			__tui_8 := tui.New(
				tui.WithText(a.statusText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
			)
			__tui_5.AddChild(__tui_8)
		} else if a.statusText(mgr.Instance().Name) == string(server.Stopping) {
			__tui_9 := tui.New(
				tui.WithText(a.statusText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_5.AddChild(__tui_9)
		} else if a.statusText(mgr.Instance().Name) == string(server.Crashed) {
			__tui_10 := tui.New(
				tui.WithText(a.statusText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
			)
			__tui_5.AddChild(__tui_10)
		} else {
			__tui_11 := tui.New(
				tui.WithText(a.statusText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_5.AddChild(__tui_11)
		}
		__tui_4.AddChild(__tui_5)
		if a.metricText(mgr.Instance().Name) != "" {
			__tui_12 := tui.New(
				tui.WithText(a.metricText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_4.AddChild(__tui_12)
		}
		if a.playersText(mgr.Instance().Name) != "" {
			__tui_13 := tui.New(
				tui.WithText(a.playersText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
			)
			__tui_4.AddChild(__tui_13)
		}
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SidebarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ConsoleViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ConsoleViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ConsoleViewView) GetRoot() *tui.Element { return v.Root }

func (v *ConsoleViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ConsoleViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ConsoleViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ConsoleViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ConsoleViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ConsoleViewView)(nil)

var _ tui.AppUnbinder = (*ConsoleViewView)(nil)

var _ tui.PropsUpdater = (*ConsoleViewView)(nil)

func ConsoleView(a *app) *ConsoleViewView {
	var view ConsoleViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, a.consoleScrollY()),
	)
	if a.logScroll.Get() > 0 {
		__tui_1 := tui.New(
			tui.WithText(fmt.Sprintf("Console — %s · scrolled (End follows live)", a.currentName())),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.New(
			tui.WithText(fmt.Sprintf("Console — %s", a.currentName())),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_0.AddChild(__tui_2)
	}
	for __idx_0, line := range a.currentLogs() {
		_ = __idx_0
		__tui_3 := tui.New(
			tui.WithText(line),
		)
		__tui_0.AddChild(__tui_3)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ConsoleViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FooterBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FooterBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FooterBarView) GetRoot() *tui.Element { return v.Root }

func (v *FooterBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FooterBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FooterBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FooterBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FooterBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FooterBarView)(nil)

var _ tui.AppUnbinder = (*FooterBarView)(nil)

var _ tui.PropsUpdater = (*FooterBarView)(nil)

func FooterBar(a *app) *FooterBarView {
	var view FooterBarView
	var watchers []tui.Watcher

	var __tui_57 *HintsRowView
	var __tui_0 *tui.Element
	if a.cmdActive.Get() {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_2 := tui.New(
			tui.WithText(fmt.Sprintf("%s >", a.currentName())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(a.cmdText.Get()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText("Enter"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("sends"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText("Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText("closes"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_9)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else if a.renActive.Get() {
		__tui_10 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_11 := tui.New(
			tui.WithText(fmt.Sprintf("Rename %s to:", a.currentName())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_10.AddChild(__tui_11)
		__tui_12 := tui.New(
			tui.WithText(a.renText.Get()),
		)
		__tui_10.AddChild(__tui_12)
		__tui_13 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_10.AddChild(__tui_13)
		if a.renMsg.Get() != "" {
			__tui_14 := tui.New(
				tui.WithText(a.renMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_10.AddChild(__tui_14)
		}
		__tui_15 := tui.New(
			tui.WithText("Enter"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_10.AddChild(__tui_15)
		__tui_16 := tui.New(
			tui.WithText("applies"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_10.AddChild(__tui_16)
		__tui_17 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_10.AddChild(__tui_17)
		__tui_18 := tui.New(
			tui.WithText("Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_10.AddChild(__tui_18)
		__tui_19 := tui.New(
			tui.WithText("cancels"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_10.AddChild(__tui_19)
		if __tui_0 == nil {
			__tui_0 = __tui_10
		}
	} else if a.memActive.Get() {
		__tui_20 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_21 := tui.New(
			tui.WithText(fmt.Sprintf("Memory (MB) for %s:", a.currentName())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_20.AddChild(__tui_21)
		__tui_22 := tui.New(
			tui.WithText(a.memText.Get()),
		)
		__tui_20.AddChild(__tui_22)
		__tui_23 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_20.AddChild(__tui_23)
		if a.memMsg.Get() != "" {
			__tui_24 := tui.New(
				tui.WithText(a.memMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_20.AddChild(__tui_24)
		}
		__tui_25 := tui.New(
			tui.WithText("Enter"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_20.AddChild(__tui_25)
		__tui_26 := tui.New(
			tui.WithText("applies on next start"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_20.AddChild(__tui_26)
		__tui_27 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_20.AddChild(__tui_27)
		__tui_28 := tui.New(
			tui.WithText("Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_20.AddChild(__tui_28)
		__tui_29 := tui.New(
			tui.WithText("cancels"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_20.AddChild(__tui_29)
		if __tui_0 == nil {
			__tui_0 = __tui_20
		}
	} else if a.schActive.Get() {
		__tui_30 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		if a.schStep.Get() == 0 {
			__tui_31 := tui.New(
				tui.WithText(fmt.Sprintf("Backup every N hours for %s (empty = off):", a.currentName())),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_30.AddChild(__tui_31)
			__tui_32 := tui.New(
				tui.WithText(a.schBackup.Get()),
			)
			__tui_30.AddChild(__tui_32)
		} else {
			__tui_33 := tui.New(
				tui.WithText("Daily restart at HH:MM (empty = off):"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_30.AddChild(__tui_33)
			__tui_34 := tui.New(
				tui.WithText(a.schRestart.Get()),
			)
			__tui_30.AddChild(__tui_34)
		}
		__tui_35 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_30.AddChild(__tui_35)
		if a.schMsg.Get() != "" {
			__tui_36 := tui.New(
				tui.WithText(a.schMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_30.AddChild(__tui_36)
		}
		__tui_37 := tui.New(
			tui.WithText("Enter"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_30.AddChild(__tui_37)
		if a.schStep.Get() == 0 {
			__tui_38 := tui.New(
				tui.WithText("next"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_30.AddChild(__tui_38)
		} else {
			__tui_39 := tui.New(
				tui.WithText("saves"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_30.AddChild(__tui_39)
		}
		__tui_40 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_30.AddChild(__tui_40)
		__tui_41 := tui.New(
			tui.WithText("Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_30.AddChild(__tui_41)
		__tui_42 := tui.New(
			tui.WithText("cancels"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_30.AddChild(__tui_42)
		if __tui_0 == nil {
			__tui_0 = __tui_30
		}
	} else if a.pkConfirm.Get() != "" {
		__tui_43 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_44 := tui.New(
			tui.WithText(a.pkConfirm.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_43.AddChild(__tui_44)
		__tui_45 := tui.New(
			tui.WithText("y"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_43.AddChild(__tui_45)
		__tui_46 := tui.New(
			tui.WithText("update"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_43.AddChild(__tui_46)
		__tui_47 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_43.AddChild(__tui_47)
		__tui_48 := tui.New(
			tui.WithText("n/Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_43.AddChild(__tui_48)
		__tui_49 := tui.New(
			tui.WithText("cancel"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_43.AddChild(__tui_49)
		if __tui_0 == nil {
			__tui_0 = __tui_43
		}
	} else if a.delTarget.Get() != "" {
		__tui_50 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_51 := tui.New(
			tui.WithText(fmt.Sprintf("Delete instance %q and ALL its files (worlds included)?", a.delTarget.Get())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_50.AddChild(__tui_51)
		__tui_52 := tui.New(
			tui.WithText("y"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_50.AddChild(__tui_52)
		__tui_53 := tui.New(
			tui.WithText("delete"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_50.AddChild(__tui_53)
		__tui_54 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_50.AddChild(__tui_54)
		__tui_55 := tui.New(
			tui.WithText("n/Esc"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_50.AddChild(__tui_55)
		__tui_56 := tui.New(
			tui.WithText("keep"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_50.AddChild(__tui_56)
		if __tui_0 == nil {
			__tui_0 = __tui_50
		}
	} else {
		__tui_57 = HintsRow(a.mainHints(), false)
		if __tui_0 == nil {
			__tui_0 = __tui_57.Root
		}
	}

	if __tui_57 != nil {
		watchers = append(watchers, __tui_57.GetWatchers()...)
	}

	__bindApp := func(app *tui.App) {
		if __tui_57 != nil {
			if binder, ok := any(__tui_57).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
	}

	__unbindApp := func() {
		if __tui_57 != nil {
			if unbinder, ok := any(__tui_57).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
	}

	view = FooterBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (a *app) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if a.splash.Get() {
		__tui_1 := app.Mount(a, 0, func() tui.Component {
			return SplashView(a)
		})
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithHeightPercent(100.00),
			tui.WithPadding(1),
			tui.WithGap(1),
		)
		__tui_3 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
			tui.WithFlexShrink(0),
		)
		__tui_4 := tui.New(
			tui.WithText("mc-tui-server"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
		)
		__tui_3.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText(fmt.Sprintf("%d instances", len(a.managers.Get()))),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_3.AddChild(__tui_5)
		__tui_2.AddChild(__tui_3)
		__tui_6 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexGrow(1),
		)
		__tui_7 := Sidebar(a)
		__tui_6.AddChild(__tui_7.Root)
		if a.wizStep.Get() != wizOff {
			__tui_8 := app.Mount(a, 1, func() tui.Component {
				return WizardView(a)
			})
			__tui_6.AddChild(__tui_8)
		} else if a.fmOpen.Get() {
			__tui_9 := app.Mount(a, 2, func() tui.Component {
				return FilesView(a)
			})
			__tui_6.AddChild(__tui_9)
		} else if a.mrOpen.Get() {
			__tui_10 := app.Mount(a, 3, func() tui.Component {
				return ModrinthView(a)
			})
			__tui_6.AddChild(__tui_10)
		} else if a.plOpen.Get() {
			__tui_11 := app.Mount(a, 4, func() tui.Component {
				return PlayersView(a)
			})
			__tui_6.AddChild(__tui_11)
		} else if a.helpOpen.Get() {
			__tui_12 := app.Mount(a, 5, func() tui.Component {
				return HelpView(a)
			})
			__tui_6.AddChild(__tui_12)
		} else {
			__tui_13 := ConsoleView(a)
			__tui_6.AddChild(__tui_13.Root)
		}
		__tui_2.AddChild(__tui_6)
		__tui_14 := FooterBar(a)
		__tui_2.AddChild(__tui_14.Root)
		if __tui_0 == nil {
			__tui_0 = __tui_2
		}
	}

	return __tui_0
}
