// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package main

import (
	"context"
	"fmt"
	"math"
	"mc-tui-server/internal/assets"
	"mc-tui-server/internal/config"
	"mc-tui-server/internal/download"
	"mc-tui-server/internal/metrics"
	"mc-tui-server/internal/properties"
	"mc-tui-server/internal/server"
	"os"
	"path/filepath"
	"strconv"
	"time"

	tui "github.com/grindlemire/go-tui"
)

const (
	stopTimeout = 30 * time.Second
	maxLogLines = 5000
)

const (
	wizOff = iota
	wizType
	wizLoading
	wizVersion
	wizName
	wizMem
	wizEula
	wizDownload
	wizError
)

var wizTypes = []config.ServerType{config.Vanilla, config.Paper, config.Purpur, config.Fabric}

type logEntry struct {
	name string
	line string
}

type app struct {
	store    *config.Store
	dataDir  string
	managers *tui.State[[]*server.Manager]
	// logCh agrega los logs de todas las instancias: los watchers se
	// registran al montar, así que un canal único permite añadir
	// instancias en caliente.
	logCh chan logEntry

	selected  *tui.State[int]
	statuses  *tui.State[map[string]server.Status]
	logs      *tui.State[map[string][]string]
	cmdActive *tui.State[bool]
	cmdText   *tui.State[string]

	collector *metrics.Collector
	samples   *tui.State[map[string]metrics.Sample]
	// lastPIDs solo se toca desde el timer de refresh (una goroutine).
	lastPIDs map[string]int

	// Estado del asistente. wizGen invalida goroutines de un asistente
	// cancelado para que no re-abran la UI.
	wizStep     *tui.State[int]
	wizGen      *tui.State[int]
	wizTypeIdx  *tui.State[int]
	wizVersions *tui.State[[]string]
	wizVerIdx   *tui.State[int]
	wizName     *tui.State[string]
	wizMemory   *tui.State[string]
	wizMsg      *tui.State[string]

	// Panel de archivos (R3). fmProps se muta fuera de un State; fmRev
	// se incrementa tras cada mutación para forzar el re-render.
	fmOpen      *tui.State[bool]
	fmTab       *tui.State[int]
	fmProps     *properties.File
	fmRev       *tui.State[int]
	fmPropsIdx  *tui.State[int]
	fmEditing   *tui.State[bool]
	fmEditText  *tui.State[string]
	fmDirty     *tui.State[bool]
	fmWorlds    *tui.State[[]string]
	fmPlugins   *tui.State[[]string]
	fmWorldIdx  *tui.State[int]
	fmPluginIdx *tui.State[int]
	fmConfirm   *tui.State[string]
	fmMsg       *tui.State[string]
}

type wizItem struct {
	Text string
	Sel  bool
}

func App(store *config.Store, managers []*server.Manager) *app {
	statuses := map[string]server.Status{}
	logs := map[string][]string{}
	for _, m := range managers {
		statuses[m.Instance().Name] = m.Status()
		logs[m.Instance().Name] = nil
	}
	a := &app{
		store:     store,
		dataDir:   filepath.Dir(store.Path()),
		managers:  tui.NewState(managers),
		logCh:     make(chan logEntry, 2048),
		selected:  tui.NewState(0),
		statuses:  tui.NewState(statuses),
		logs:      tui.NewState(logs),
		cmdActive: tui.NewState(false),
		cmdText:   tui.NewState(""),
		collector: metrics.NewCollector(),
		samples:   tui.NewState(map[string]metrics.Sample{}),
		lastPIDs:  map[string]int{},

		wizStep:     tui.NewState(wizOff),
		wizGen:      tui.NewState(0),
		wizTypeIdx:  tui.NewState(0),
		wizVersions: tui.NewState([]string{}),
		wizVerIdx:   tui.NewState(0),
		wizName:     tui.NewState(""),
		wizMemory:   tui.NewState(""),
		wizMsg:      tui.NewState(""),

		fmOpen:      tui.NewState(false),
		fmTab:       tui.NewState(0),
		fmProps:     &properties.File{},
		fmRev:       tui.NewState(0),
		fmPropsIdx:  tui.NewState(0),
		fmEditing:   tui.NewState(false),
		fmEditText:  tui.NewState(""),
		fmDirty:     tui.NewState(false),
		fmWorlds:    tui.NewState([]string{}),
		fmPlugins:   tui.NewState([]string{}),
		fmWorldIdx:  tui.NewState(0),
		fmPluginIdx: tui.NewState(0),
		fmConfirm:   tui.NewState(""),
		fmMsg:       tui.NewState(""),
	}
	for _, m := range managers {
		a.pumpLogs(m)
	}
	return a
}

func (a *app) pumpLogs(m *server.Manager) {
	name := m.Instance().Name
	go func() {
		for line := range m.Logs() {
			a.logCh <- logEntry{name: name, line: line}
		}
	}()
}

func (a *app) current() *server.Manager {
	managers := a.managers.Get()
	i := a.selected.Get()
	if i < 0 || i >= len(managers) {
		return nil
	}
	return managers[i]
}

func (a *app) moveSelection(delta int) {
	n := len(a.managers.Get())
	if n == 0 {
		return
	}
	a.selected.Update(func(i int) int {
		i += delta
		if i < 0 {
			i = 0
		}
		if i >= n {
			i = n - 1
		}
		return i
	})
}

func (a *app) appendLog(name, line string) {
	a.logs.Update(func(m map[string][]string) map[string][]string {
		lines := append(m[name], line)
		if len(lines) > maxLogLines {
			lines = lines[len(lines)-maxLogLines:]
		}
		m[name] = lines
		return m
	})
}

func (a *app) refreshStatuses() {
	a.statuses.Update(func(m map[string]server.Status) map[string]server.Status {
		for _, mgr := range a.managers.Get() {
			m[mgr.Instance().Name] = mgr.Status()
		}
		return m
	})
	a.refreshSamples()
}

func (a *app) refreshSamples() {
	a.samples.Update(func(m map[string]metrics.Sample) map[string]metrics.Sample {
		for _, mgr := range a.managers.Get() {
			name := mgr.Instance().Name
			pid := mgr.PID()
			if old := a.lastPIDs[name]; old != 0 && old != pid {
				a.collector.Forget(old)
			}
			a.lastPIDs[name] = pid
			if pid == 0 {
				delete(m, name)
				continue
			}
			s, err := a.collector.Sample(pid)
			if err != nil {
				// El proceso pudo morir entre PID() y Sample(); se limpia solo.
				delete(m, name)
				continue
			}
			m[name] = s
		}
		return m
	})
}

func (a *app) metricText(name string) string {
	s, ok := a.samples.Get()[name]
	if !ok {
		return ""
	}
	return fmt.Sprintf("cpu %.1f%% · ram %dM", s.CPUPercent, s.RSSBytes/(1024*1024))
}

func (a *app) startSelected() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	go func() {
		if err := mgr.Start(); err != nil {
			a.appendLog(mgr.Instance().Name, "[mc-tui] "+err.Error())
		}
	}()
}

func (a *app) stopSelected() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	go func() {
		if err := mgr.Stop(stopTimeout); err != nil {
			a.appendLog(mgr.Instance().Name, "[mc-tui] "+err.Error())
		}
	}()
}

func (a *app) restartSelected() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	go func() {
		if err := mgr.Restart(stopTimeout); err != nil {
			a.appendLog(mgr.Instance().Name, "[mc-tui] "+err.Error())
		}
	}()
}

func (a *app) appendCmdChar(ke tui.KeyEvent) {
	a.cmdText.Update(func(s string) string { return s + string(ke.Rune) })
}

func (a *app) deleteCmdChar(ke tui.KeyEvent) {
	a.cmdText.Update(func(s string) string {
		r := []rune(s)
		if len(r) == 0 {
			return s
		}
		return string(r[:len(r)-1])
	})
}

func (a *app) submitCmd(ke tui.KeyEvent) {
	text := a.cmdText.Get()
	a.cmdText.Set("")
	if text == "" {
		return
	}
	mgr := a.current()
	if mgr == nil {
		return
	}
	a.appendLog(mgr.Instance().Name, "> "+text)
	if err := mgr.Send(text); err != nil {
		a.appendLog(mgr.Instance().Name, "[mc-tui] "+err.Error())
	}
}

func (a *app) closeCmd(ke tui.KeyEvent) {
	a.cmdActive.Set(false)
	a.cmdText.Set("")
}

func (a *app) wizOpen() {
	a.wizGen.Update(func(g int) int { return g + 1 })
	a.wizTypeIdx.Set(0)
	a.wizVersions.Set([]string{})
	a.wizVerIdx.Set(0)
	a.wizName.Set("")
	a.wizMemory.Set("")
	a.wizMsg.Set("")
	a.wizStep.Set(wizType)
}

func (a *app) wizClose() {
	a.wizGen.Update(func(g int) int { return g + 1 })
	a.wizStep.Set(wizOff)
}

func (a *app) wizFail(gen int, err error) {
	if a.wizGen.Get() != gen {
		return
	}
	a.wizMsg.Set("Error: " + err.Error())
	a.wizStep.Set(wizError)
}

func (a *app) wizFetchVersions() {
	typ := wizTypes[a.wizTypeIdx.Get()]
	gen := a.wizGen.Get()
	a.wizMsg.Set(fmt.Sprintf("Consultando versiones de %s...", typ))
	a.wizStep.Set(wizLoading)
	go func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		prov, err := download.For(typ, nil)
		if err != nil {
			a.wizFail(gen, err)
			return
		}
		versions, err := prov.Versions(ctx)
		if err != nil {
			a.wizFail(gen, err)
			return
		}
		if len(versions) == 0 {
			a.wizFail(gen, fmt.Errorf("la API de %s no devolvió versiones", typ))
			return
		}
		if a.wizGen.Get() != gen {
			return
		}
		a.wizVersions.Set(versions)
		a.wizVerIdx.Set(0)
		a.wizStep.Set(wizVersion)
	}()
}

func validNameChar(r rune) bool {
	switch {
	case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
		return true
	}
	return false
}

func (a *app) wizSubmitName() {
	name := a.wizName.Get()
	if name == "" {
		a.wizMsg.Set("El nombre no puede estar vacío")
		return
	}
	if _, exists := a.store.Get(name); exists {
		a.wizMsg.Set(fmt.Sprintf("Ya existe una instancia llamada %q", name))
		return
	}
	a.wizMsg.Set("")
	a.wizStep.Set(wizMem)
}

func (a *app) wizMemoryMB() int {
	mb, err := strconv.Atoi(a.wizMemory.Get())
	if err != nil || mb <= 0 {
		return 2048
	}
	return mb
}

func (a *app) wizStartDownload() {
	typ := wizTypes[a.wizTypeIdx.Get()]
	version := a.wizVersions.Get()[a.wizVerIdx.Get()]
	name := a.wizName.Get()
	memMB := a.wizMemoryMB()
	gen := a.wizGen.Get()
	a.wizMsg.Set("Resolviendo URL de descarga...")
	a.wizStep.Set(wizDownload)
	go func() {
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Minute)
		defer cancel()
		prov, err := download.For(typ, nil)
		if err != nil {
			a.wizFail(gen, err)
			return
		}
		url, err := prov.ResolveJarURL(ctx, version)
		if err != nil {
			a.wizFail(gen, err)
			return
		}
		dir := filepath.Join(a.dataDir, "servers", name)
		jar := filepath.Join(dir, "server.jar")
		err = download.DownloadFile(ctx, nil, url, jar, func(done, total int64) {
			if total > 0 {
				a.wizMsg.Set(fmt.Sprintf("Descargando... %d%% (%dMB de %dMB)",
					done*100/total, done/(1024*1024), total/(1024*1024)))
			} else {
				a.wizMsg.Set(fmt.Sprintf("Descargando... %dMB", done/(1024*1024)))
			}
		})
		if err != nil {
			a.wizFail(gen, err)
			return
		}
		// El usuario aceptó el EULA en el paso anterior del asistente.
		if err := os.WriteFile(filepath.Join(dir, "eula.txt"), []byte("eula=true\n"), 0o644); err != nil {
			a.wizFail(gen, err)
			return
		}
		inst := config.Instance{
			Name:     name,
			Dir:      dir,
			JarPath:  "server.jar",
			MemoryMB: memMB,
			Type:     typ,
			Version:  version,
		}
		if err := a.store.Add(inst); err != nil {
			a.wizFail(gen, err)
			return
		}
		if err := a.store.Save(); err != nil {
			a.wizFail(gen, err)
			return
		}
		mgr := server.New(inst)
		a.pumpLogs(mgr)
		a.managers.Update(func(ms []*server.Manager) []*server.Manager {
			return append(ms, mgr)
		})
		a.appendLog(name, fmt.Sprintf("[mc-tui] Instancia creada: %s %s (%d MB)", typ, version, memMB))
		a.selected.Set(len(a.managers.Get()) - 1)
		a.wizClose()
	}()
}

func (a *app) wizTypeItems() []wizItem {
	items := make([]wizItem, len(wizTypes))
	for i, t := range wizTypes {
		items[i] = wizItem{Text: string(t), Sel: i == a.wizTypeIdx.Get()}
	}
	return items
}

func (a *app) wizVersionItems() []wizItem {
	return windowItems(a.wizVersions.Get(), a.wizVerIdx.Get(), 12)
}

func (a *app) wizMoveType(delta int) {
	a.wizTypeIdx.Update(func(i int) int {
		i += delta
		if i < 0 {
			i = 0
		}
		if i >= len(wizTypes) {
			i = len(wizTypes) - 1
		}
		return i
	})
}

func (a *app) wizMoveVersion(delta int) {
	n := len(a.wizVersions.Get())
	a.wizVerIdx.Update(func(i int) int {
		i += delta
		if i < 0 {
			i = 0
		}
		if i >= n {
			i = n - 1
		}
		return i
	})
}

func (a *app) wizKeyMap() tui.KeyMap {
	esc := tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.wizClose() })
	switch a.wizStep.Get() {
	case wizType:
		return tui.KeyMap{
			tui.OnStop(tui.KeyUp, func(ke tui.KeyEvent) { a.wizMoveType(-1) }),
			tui.OnStop(tui.KeyDown, func(ke tui.KeyEvent) { a.wizMoveType(1) }),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.wizFetchVersions() }),
			esc,
		}
	case wizLoading:
		return tui.KeyMap{esc}
	case wizVersion:
		return tui.KeyMap{
			tui.OnStop(tui.KeyUp, func(ke tui.KeyEvent) { a.wizMoveVersion(-1) }),
			tui.OnStop(tui.KeyDown, func(ke tui.KeyEvent) { a.wizMoveVersion(1) }),
			tui.OnStop(tui.KeyPageUp, func(ke tui.KeyEvent) { a.wizMoveVersion(-10) }),
			tui.OnStop(tui.KeyPageDown, func(ke tui.KeyEvent) { a.wizMoveVersion(10) }),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.wizStep.Set(wizName) }),
			esc,
		}
	case wizName:
		return tui.KeyMap{
			tui.OnStop(tui.AnyRune, func(ke tui.KeyEvent) {
				if validNameChar(ke.Rune) {
					a.wizName.Update(func(s string) string { return s + string(ke.Rune) })
				}
			}),
			tui.OnStop(tui.KeyBackspace, func(ke tui.KeyEvent) {
				a.wizName.Update(func(s string) string {
					if len(s) == 0 {
						return s
					}
					return s[:len(s)-1]
				})
			}),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.wizSubmitName() }),
			esc,
		}
	case wizMem:
		return tui.KeyMap{
			tui.OnStop(tui.AnyRune, func(ke tui.KeyEvent) {
				if ke.Rune >= '0' && ke.Rune <= '9' {
					a.wizMemory.Update(func(s string) string { return s + string(ke.Rune) })
				}
			}),
			tui.OnStop(tui.KeyBackspace, func(ke tui.KeyEvent) {
				a.wizMemory.Update(func(s string) string {
					if len(s) == 0 {
						return s
					}
					return s[:len(s)-1]
				})
			}),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.wizStep.Set(wizEula) }),
			esc,
		}
	case wizEula:
		return tui.KeyMap{
			tui.OnStop(tui.Rune('s'), func(ke tui.KeyEvent) { a.wizStartDownload() }),
			tui.OnStop(tui.Rune('n'), func(ke tui.KeyEvent) { a.wizClose() }),
			esc,
		}
	case wizDownload:
		// Sin teclas: la descarga no se cancela a mitad en esta versión.
		return tui.KeyMap{tui.OnStop(tui.AnyRune, func(ke tui.KeyEvent) {})}
	default: // wizError
		return tui.KeyMap{esc, tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.wizClose() })}
	}
}

func (a *app) fmOpenPanel() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	inst := mgr.Instance()
	a.fmTab.Set(0)
	a.fmPropsIdx.Set(0)
	a.fmWorldIdx.Set(0)
	a.fmPluginIdx.Set(0)
	a.fmEditing.Set(false)
	a.fmDirty.Set(false)
	a.fmConfirm.Set("")
	a.fmMsg.Set("")

	props, err := properties.Load(filepath.Join(inst.Dir, "server.properties"))
	if err != nil {
		a.fmMsg.Set("Error: " + err.Error())
		props = &properties.File{}
	}
	a.fmProps = props
	a.fmReloadLists(inst)
	a.fmRev.Update(func(r int) int { return r + 1 })
	a.fmOpen.Set(true)
}

func (a *app) fmReloadLists(inst config.Instance) {
	worlds, err := assets.Worlds(inst.Dir)
	if err != nil {
		a.fmMsg.Set("Error: " + err.Error())
	}
	a.fmWorlds.Set(worlds)
	plugins, err := assets.Plugins(inst.Dir, inst.Type)
	if err != nil {
		a.fmMsg.Set("Error: " + err.Error())
	}
	a.fmPlugins.Set(plugins)
}

func (a *app) fmClose() {
	a.fmOpen.Set(false)
}

func (a *app) fmPropLines() []string {
	keys := a.fmProps.Keys()
	out := make([]string, len(keys))
	for i, k := range keys {
		v, _ := a.fmProps.Get(k)
		out[i] = k + "=" + v
	}
	return out
}

func windowItems(list []string, sel, window int) []wizItem {
	start := sel - window/2
	if start < 0 {
		start = 0
	}
	end := start + window
	if end > len(list) {
		end = len(list)
		if start = end - window; start < 0 {
			start = 0
		}
	}
	items := make([]wizItem, 0, end-start)
	for i := start; i < end; i++ {
		items = append(items, wizItem{Text: list[i], Sel: i == sel})
	}
	return items
}

func (a *app) fmItems() []wizItem {
	switch a.fmTab.Get() {
	case 0:
		return windowItems(a.fmPropLines(), a.fmPropsIdx.Get(), 16)
	case 1:
		return windowItems(a.fmWorlds.Get(), a.fmWorldIdx.Get(), 16)
	default:
		return windowItems(a.fmPlugins.Get(), a.fmPluginIdx.Get(), 16)
	}
}

func (a *app) fmMove(delta int) {
	move := func(st *tui.State[int], n int) {
		if n == 0 {
			return
		}
		st.Update(func(i int) int {
			i += delta
			if i < 0 {
				i = 0
			}
			if i >= n {
				i = n - 1
			}
			return i
		})
	}
	switch a.fmTab.Get() {
	case 0:
		move(a.fmPropsIdx, len(a.fmProps.Keys()))
	case 1:
		move(a.fmWorldIdx, len(a.fmWorlds.Get()))
	default:
		move(a.fmPluginIdx, len(a.fmPlugins.Get()))
	}
}

func (a *app) fmSelectedKey() string {
	keys := a.fmProps.Keys()
	i := a.fmPropsIdx.Get()
	if i < 0 || i >= len(keys) {
		return ""
	}
	return keys[i]
}

func (a *app) fmBeginEdit() {
	key := a.fmSelectedKey()
	if key == "" {
		return
	}
	v, _ := a.fmProps.Get(key)
	a.fmEditText.Set(v)
	a.fmEditing.Set(true)
	a.fmMsg.Set("")
}

func (a *app) fmCommitEdit() {
	key := a.fmSelectedKey()
	a.fmProps.Set(key, a.fmEditText.Get())
	a.fmDirty.Set(true)
	a.fmEditing.Set(false)
	a.fmRev.Update(func(r int) int { return r + 1 })
	a.fmMsg.Set("Cambio en memoria; pulsa w para guardar")
}

func (a *app) fmSave() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	path := filepath.Join(mgr.Instance().Dir, "server.properties")
	if err := a.fmProps.Save(path); err != nil {
		a.fmMsg.Set("Error: " + err.Error())
		return
	}
	a.fmDirty.Set(false)
	a.fmMsg.Set("Guardado. Reinicia el servidor para aplicar los cambios")
}

func (a *app) fmAskDelete() {
	mgr := a.current()
	if mgr == nil {
		return
	}
	if mgr.Status() != server.Stopped {
		a.fmMsg.Set("Detén el servidor antes de borrar archivos")
		return
	}
	var name string
	switch a.fmTab.Get() {
	case 1:
		if ws := a.fmWorlds.Get(); len(ws) > 0 {
			name = ws[a.fmWorldIdx.Get()]
		}
	case 2:
		if ps := a.fmPlugins.Get(); len(ps) > 0 {
			name = ps[a.fmPluginIdx.Get()]
		}
	}
	if name == "" {
		return
	}
	a.fmConfirm.Set(name)
}

func (a *app) fmDoDelete() {
	mgr := a.current()
	name := a.fmConfirm.Get()
	a.fmConfirm.Set("")
	if mgr == nil || name == "" {
		return
	}
	inst := mgr.Instance()
	var err error
	if a.fmTab.Get() == 1 {
		err = assets.DeleteWorld(inst.Dir, name)
	} else {
		err = assets.DeletePlugin(inst.Dir, inst.Type, name)
	}
	if err != nil {
		a.fmMsg.Set("Error: " + err.Error())
		return
	}
	a.fmMsg.Set(fmt.Sprintf("%q eliminado", name))
	a.fmWorldIdx.Set(0)
	a.fmPluginIdx.Set(0)
	a.fmReloadLists(inst)
}

func (a *app) fmTitle() string {
	_ = a.fmRev.Get() // dependencia explícita: re-render tras mutar fmProps
	title := fmt.Sprintf("Archivos — %s · %s", a.currentName(), a.fmTabName())
	if a.fmDirty.Get() {
		title += " (sin guardar)"
	}
	return title
}

func (a *app) fmHelp() string {
	if a.fmTab.Get() == 0 {
		return "↑/↓ elegir | Enter editar | w guardar | 1/2/3 o Tab pestaña | Esc cerrar"
	}
	return "↑/↓ elegir | d borrar | 1/2/3 o Tab pestaña | Esc cerrar"
}

func (a *app) fmTabName() string {
	switch a.fmTab.Get() {
	case 0:
		return "Propiedades"
	case 1:
		return "Mundos"
	default:
		return "Plugins/Mods"
	}
}

func (a *app) fmKeyMap() tui.KeyMap {
	if a.fmEditing.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.AnyRune, func(ke tui.KeyEvent) {
				a.fmEditText.Update(func(s string) string { return s + string(ke.Rune) })
			}),
			tui.OnStop(tui.KeyBackspace, func(ke tui.KeyEvent) {
				a.fmEditText.Update(func(s string) string {
					r := []rune(s)
					if len(r) == 0 {
						return s
					}
					return string(r[:len(r)-1])
				})
			}),
			tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) { a.fmCommitEdit() }),
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.fmEditing.Set(false) }),
		}
	}
	if a.fmConfirm.Get() != "" {
		return tui.KeyMap{
			tui.OnStop(tui.Rune('s'), func(ke tui.KeyEvent) { a.fmDoDelete() }),
			tui.OnStop(tui.Rune('n'), func(ke tui.KeyEvent) { a.fmConfirm.Set("") }),
			tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.fmConfirm.Set("") }),
		}
	}
	return tui.KeyMap{
		tui.OnStop(tui.Rune('1'), func(ke tui.KeyEvent) { a.fmTab.Set(0) }),
		tui.OnStop(tui.Rune('2'), func(ke tui.KeyEvent) { a.fmTab.Set(1) }),
		tui.OnStop(tui.Rune('3'), func(ke tui.KeyEvent) { a.fmTab.Set(2) }),
		tui.OnStop(tui.KeyTab, func(ke tui.KeyEvent) { a.fmTab.Update(func(t int) int { return (t + 1) % 3 }) }),
		tui.OnStop(tui.KeyUp, func(ke tui.KeyEvent) { a.fmMove(-1) }),
		tui.OnStop(tui.KeyDown, func(ke tui.KeyEvent) { a.fmMove(1) }),
		tui.OnStop(tui.KeyPageUp, func(ke tui.KeyEvent) { a.fmMove(-10) }),
		tui.OnStop(tui.KeyPageDown, func(ke tui.KeyEvent) { a.fmMove(10) }),
		tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			if a.fmTab.Get() == 0 {
				a.fmBeginEdit()
			}
		}),
		tui.OnStop(tui.Rune('w'), func(ke tui.KeyEvent) {
			if a.fmTab.Get() == 0 {
				a.fmSave()
			}
		}),
		tui.OnStop(tui.Rune('d'), func(ke tui.KeyEvent) {
			if a.fmTab.Get() != 0 {
				a.fmAskDelete()
			}
		}),
		tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { a.fmClose() }),
	}
}

func (a *app) KeyMap() tui.KeyMap {
	if a.wizStep.Get() != wizOff {
		return a.wizKeyMap()
	}
	if a.fmOpen.Get() {
		return a.fmKeyMap()
	}
	if a.cmdActive.Get() {
		return tui.KeyMap{
			tui.OnStop(tui.AnyRune, a.appendCmdChar),
			tui.OnStop(tui.KeyBackspace, a.deleteCmdChar),
			tui.OnStop(tui.KeyEnter, a.submitCmd),
			tui.OnStop(tui.KeyEscape, a.closeCmd),
		}
	}
	return tui.KeyMap{
		tui.On(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('c'), func(ke tui.KeyEvent) { a.cmdActive.Set(true) }),
		tui.On(tui.KeyEnter, func(ke tui.KeyEvent) { a.cmdActive.Set(true) }),
		tui.On(tui.Rune('n'), func(ke tui.KeyEvent) { a.wizOpen() }),
		tui.On(tui.Rune('e'), func(ke tui.KeyEvent) { a.fmOpenPanel() }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { a.moveSelection(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { a.moveSelection(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { a.moveSelection(-1) }),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { a.moveSelection(1) }),
		tui.On(tui.Rune('s'), func(ke tui.KeyEvent) { a.startSelected() }),
		tui.On(tui.Rune('x'), func(ke tui.KeyEvent) { a.stopSelected() }),
		tui.On(tui.Rune('r'), func(ke tui.KeyEvent) { a.restartSelected() }),
	}
}

func (a *app) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnTimer(500*time.Millisecond, a.refreshStatuses),
		tui.Watch(a.logCh, func(e logEntry) { a.appendLog(e.name, e.line) }),
	}
}

func (a *app) rowClass(i int) string {
	if i == a.selected.Get() {
		return "font-bold text-cyan"
	}
	return ""
}

func (a *app) statusClass(name string) string {
	switch a.statuses.Get()[name] {
	case server.Running:
		return "text-green"
	case server.Stopping:
		return "text-yellow"
	default:
		return "font-dim"
	}
}

func (a *app) statusText(name string) string {
	st := a.statuses.Get()[name]
	if st == "" {
		st = server.Stopped
	}
	return string(st)
}

func (a *app) currentLogs() []string {
	mgr := a.current()
	if mgr == nil {
		return nil
	}
	return a.logs.Get()[mgr.Instance().Name]
}

func (a *app) currentName() string {
	mgr := a.current()
	if mgr == nil {
		return "sin instancia"
	}
	return mgr.Instance().Name
}

func (a *app) wizStepTitle() string {
	switch a.wizStep.Get() {
	case wizType:
		return "1/5 · Tipo de servidor"
	case wizLoading:
		return "2/5 · Consultando versiones"
	case wizVersion:
		return "2/5 · Versión"
	case wizName:
		return "3/5 · Nombre de la instancia"
	case wizMem:
		return "4/5 · Memoria (MB)"
	case wizEula:
		return "5/5 · EULA de Minecraft"
	case wizDownload:
		return "Descargando"
	default:
		return "Error"
	}
}

func (a *app) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("mc-tui-server"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(fmt.Sprintf("%d instancias", len(a.managers.Get()))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithFlexShrink(0),
		tui.WithMinWidth(30),
	)
	__tui_6 := tui.New(
		tui.WithText("Instancias"),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_6)
	if len(a.managers.Get()) == 0 {
		__tui_7 := tui.New(
			tui.WithText("No hay instancias."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_5.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText("Pulsa n para crear una"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_5.AddChild(__tui_8)
	}
	for i, mgr := range a.managers.Get() {
		_ = i
		__tui_9 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		__tui_10 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
		)
		__tui_11 := tui.New(
			tui.WithText(mgr.Instance().Name),
		)
		__tui_10.AddChild(__tui_11)
		__tui_12 := tui.New(
			tui.WithText(a.statusText(mgr.Instance().Name)),
		)
		__tui_10.AddChild(__tui_12)
		__tui_9.AddChild(__tui_10)
		if a.metricText(mgr.Instance().Name) != "" {
			__tui_13 := tui.New(
				tui.WithText(a.metricText(mgr.Instance().Name)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_9.AddChild(__tui_13)
		}
		__tui_5.AddChild(__tui_9)
	}
	__tui_4.AddChild(__tui_5)
	if a.wizStep.Get() != wizOff {
		__tui_14 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
			tui.WithPadding(1),
			tui.WithFlexGrow(1),
			tui.WithGap(1),
		)
		__tui_15 := tui.New(
			tui.WithText(fmt.Sprintf("Nueva instancia — %s", a.wizStepTitle())),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
		)
		__tui_14.AddChild(__tui_15)
		if a.wizStep.Get() == wizType {
			for __idx_0, item := range a.wizTypeItems() {
				_ = __idx_0
				if item.Sel {
					__tui_16 := tui.New(
						tui.WithText(fmt.Sprintf("> %s", item.Text)),
						tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
					)
					__tui_14.AddChild(__tui_16)
				} else {
					__tui_17 := tui.New(
						tui.WithText(fmt.Sprintf("  %s", item.Text)),
					)
					__tui_14.AddChild(__tui_17)
				}
			}
			__tui_18 := tui.New(
				tui.WithText("↑/↓ elegir | Enter continuar | Esc cancelar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_18)
		}
		if a.wizStep.Get() == wizLoading {
			__tui_19 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_14.AddChild(__tui_19)
			__tui_20 := tui.New(
				tui.WithText("Esc cancelar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_20)
		}
		if a.wizStep.Get() == wizVersion {
			for __idx_0, item := range a.wizVersionItems() {
				_ = __idx_0
				if item.Sel {
					__tui_21 := tui.New(
						tui.WithText(fmt.Sprintf("> %s", item.Text)),
						tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
					)
					__tui_14.AddChild(__tui_21)
				} else {
					__tui_22 := tui.New(
						tui.WithText(fmt.Sprintf("  %s", item.Text)),
					)
					__tui_14.AddChild(__tui_22)
				}
			}
			__tui_23 := tui.New(
				tui.WithText("↑/↓/PgUp/PgDn elegir | Enter continuar | Esc cancelar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_23)
		}
		if a.wizStep.Get() == wizName {
			__tui_24 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			__tui_25 := tui.New(
				tui.WithText("Nombre:"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_24.AddChild(__tui_25)
			__tui_26 := tui.New(
				tui.WithText(a.wizName.Get()),
			)
			__tui_24.AddChild(__tui_26)
			__tui_27 := tui.New(
				tui.WithText("_"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
			)
			__tui_24.AddChild(__tui_27)
			__tui_14.AddChild(__tui_24)
			if a.wizMsg.Get() != "" {
				__tui_28 := tui.New(
					tui.WithText(a.wizMsg.Get()),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
				)
				__tui_14.AddChild(__tui_28)
			}
			__tui_29 := tui.New(
				tui.WithText("letras, números, - y _ | Enter continuar | Esc cancelar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_29)
		}
		if a.wizStep.Get() == wizMem {
			__tui_30 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			__tui_31 := tui.New(
				tui.WithText("Memoria (MB):"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_30.AddChild(__tui_31)
			__tui_32 := tui.New(
				tui.WithText(a.wizMemory.Get()),
			)
			__tui_30.AddChild(__tui_32)
			__tui_33 := tui.New(
				tui.WithText("_"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
			)
			__tui_30.AddChild(__tui_33)
			__tui_14.AddChild(__tui_30)
			__tui_34 := tui.New(
				tui.WithText("vacío = 2048 | Enter continuar | Esc cancelar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_34)
		}
		if a.wizStep.Get() == wizEula {
			__tui_35 := tui.New(
				tui.WithText("Para ejecutar el servidor debes aceptar el EULA de Minecraft:"),
			)
			__tui_14.AddChild(__tui_35)
			__tui_36 := tui.New(
				tui.WithText("https://aka.ms/MinecraftEULA"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
			)
			__tui_14.AddChild(__tui_36)
			__tui_37 := tui.New(
				tui.WithText("¿Aceptas? (s = sí y descargar, n/Esc = cancelar)"),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_14.AddChild(__tui_37)
		}
		if a.wizStep.Get() == wizDownload {
			__tui_38 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_14.AddChild(__tui_38)
		}
		if a.wizStep.Get() == wizError {
			__tui_39 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_14.AddChild(__tui_39)
			__tui_40 := tui.New(
				tui.WithText("Esc cerrar"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_14.AddChild(__tui_40)
		}
		__tui_4.AddChild(__tui_14)
	} else if a.fmOpen.Get() {
		__tui_41 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
			tui.WithPadding(1),
			tui.WithFlexGrow(1),
		)
		__tui_42 := tui.New(
			tui.WithText(a.fmTitle()),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
		)
		__tui_41.AddChild(__tui_42)
		__tui_43 := tui.New(
			tui.WithText("1 Propiedades | 2 Mundos | 3 Plugins/Mods"),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_41.AddChild(__tui_43)
		if len(a.fmItems()) == 0 {
			__tui_44 := tui.New(
				tui.WithText("(no hay elementos)"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_41.AddChild(__tui_44)
		}
		for __idx_0, item := range a.fmItems() {
			_ = __idx_0
			if item.Sel {
				__tui_45 := tui.New(
					tui.WithText(fmt.Sprintf("> %s", item.Text)),
					tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
				)
				__tui_41.AddChild(__tui_45)
			} else {
				__tui_46 := tui.New(
					tui.WithText(fmt.Sprintf("  %s", item.Text)),
				)
				__tui_41.AddChild(__tui_46)
			}
		}
		if a.fmEditing.Get() {
			__tui_47 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			__tui_48 := tui.New(
				tui.WithText(fmt.Sprintf("%s =", a.fmSelectedKey())),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_47.AddChild(__tui_48)
			__tui_49 := tui.New(
				tui.WithText(a.fmEditText.Get()),
			)
			__tui_47.AddChild(__tui_49)
			__tui_50 := tui.New(
				tui.WithText("_"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
			)
			__tui_47.AddChild(__tui_50)
			__tui_51 := tui.New(
				tui.WithText("(Enter aplica | Esc cancela)"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_47.AddChild(__tui_51)
			__tui_41.AddChild(__tui_47)
		}
		if a.fmConfirm.Get() != "" {
			__tui_52 := tui.New(
				tui.WithText(fmt.Sprintf("¿Borrar %q definitivamente? (s = sí, n = no)", a.fmConfirm.Get())),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
			)
			__tui_41.AddChild(__tui_52)
		}
		if a.fmMsg.Get() != "" {
			__tui_53 := tui.New(
				tui.WithText(a.fmMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_41.AddChild(__tui_53)
		}
		__tui_54 := tui.New(
			tui.WithText(a.fmHelp()),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_41.AddChild(__tui_54)
		__tui_4.AddChild(__tui_41)
	} else {
		__tui_55 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithPadding(1),
			tui.WithFlexGrow(1),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, math.MaxInt),
		)
		__tui_56 := tui.New(
			tui.WithText(fmt.Sprintf("Consola — %s", a.currentName())),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_55.AddChild(__tui_56)
		for __idx_0, line := range a.currentLogs() {
			_ = __idx_0
			__tui_57 := tui.New(
				tui.WithText(line),
			)
			__tui_55.AddChild(__tui_57)
		}
		__tui_4.AddChild(__tui_55)
	}
	__tui_0.AddChild(__tui_4)
	if a.cmdActive.Get() {
		__tui_58 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_59 := tui.New(
			tui.WithText(fmt.Sprintf("%s >", a.currentName())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_58.AddChild(__tui_59)
		__tui_60 := tui.New(
			tui.WithText(a.cmdText.Get()),
		)
		__tui_58.AddChild(__tui_60)
		__tui_61 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_58.AddChild(__tui_61)
		__tui_62 := tui.New(
			tui.WithText("(Enter envía | Esc cierra)"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_58.AddChild(__tui_62)
		__tui_0.AddChild(__tui_58)
	} else {
		__tui_63 := tui.New(
			tui.WithText("↑/↓ seleccionar | s iniciar | x detener | r reiniciar | c/Enter comando | e archivos | n nueva | q salir"),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_63)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (a *app) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*app)
	if !ok {
		return
	}
	a.store = f.store
	a.dataDir = f.dataDir
	a.collector = f.collector
	a.lastPIDs = f.lastPIDs
	a.fmProps = f.fmProps
}

func (a *app) UpdateProps(fresh tui.Component) {
	a.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*app)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *app) bindAppFields(app *tui.App) {
	if a.managers != nil {
		a.managers.BindApp(app)
	}
	if a.selected != nil {
		a.selected.BindApp(app)
	}
	if a.statuses != nil {
		a.statuses.BindApp(app)
	}
	if a.logs != nil {
		a.logs.BindApp(app)
	}
	if a.cmdActive != nil {
		a.cmdActive.BindApp(app)
	}
	if a.cmdText != nil {
		a.cmdText.BindApp(app)
	}
	if a.samples != nil {
		a.samples.BindApp(app)
	}
	if a.wizStep != nil {
		a.wizStep.BindApp(app)
	}
	if a.wizGen != nil {
		a.wizGen.BindApp(app)
	}
	if a.wizTypeIdx != nil {
		a.wizTypeIdx.BindApp(app)
	}
	if a.wizVersions != nil {
		a.wizVersions.BindApp(app)
	}
	if a.wizVerIdx != nil {
		a.wizVerIdx.BindApp(app)
	}
	if a.wizName != nil {
		a.wizName.BindApp(app)
	}
	if a.wizMemory != nil {
		a.wizMemory.BindApp(app)
	}
	if a.wizMsg != nil {
		a.wizMsg.BindApp(app)
	}
	if a.fmOpen != nil {
		a.fmOpen.BindApp(app)
	}
	if a.fmTab != nil {
		a.fmTab.BindApp(app)
	}
	if a.fmRev != nil {
		a.fmRev.BindApp(app)
	}
	if a.fmPropsIdx != nil {
		a.fmPropsIdx.BindApp(app)
	}
	if a.fmEditing != nil {
		a.fmEditing.BindApp(app)
	}
	if a.fmEditText != nil {
		a.fmEditText.BindApp(app)
	}
	if a.fmDirty != nil {
		a.fmDirty.BindApp(app)
	}
	if a.fmWorlds != nil {
		a.fmWorlds.BindApp(app)
	}
	if a.fmPlugins != nil {
		a.fmPlugins.BindApp(app)
	}
	if a.fmWorldIdx != nil {
		a.fmWorldIdx.BindApp(app)
	}
	if a.fmPluginIdx != nil {
		a.fmPluginIdx.BindApp(app)
	}
	if a.fmConfirm != nil {
		a.fmConfirm.BindApp(app)
	}
	if a.fmMsg != nil {
		a.fmMsg.BindApp(app)
	}
}

func (a *app) BindApp(app *tui.App) {
	a.bindAppFields(app)
}

var _ tui.AppBinder = (*app)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener     = (*app)(nil)
	_ tui.WatcherProvider = (*app)(nil)
)
