// Code generated by tui generate. DO NOT EDIT.
// Source: files_view.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type FilesViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FilesViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FilesViewView) GetRoot() *tui.Element { return v.Root }

func (v *FilesViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FilesViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FilesViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FilesViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FilesViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FilesViewView)(nil)

var _ tui.AppUnbinder = (*FilesViewView)(nil)

var _ tui.PropsUpdater = (*FilesViewView)(nil)

func FilesView(a *app) *FilesViewView {
	var view FilesViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText(a.fmTitle()),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_3 := tui.New(
		tui.WithText("1"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_3)
	if a.fmTab.Get() == 0 {
		__tui_4 := tui.New(
			tui.WithText("Properties"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_4)
	} else {
		__tui_5 := tui.New(
			tui.WithText("Properties"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_5)
	}
	__tui_6 := tui.New(
		tui.WithText("2"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_6)
	if a.fmTab.Get() == 1 {
		__tui_7 := tui.New(
			tui.WithText("Worlds"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_7)
	} else {
		__tui_8 := tui.New(
			tui.WithText("Worlds"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_8)
	}
	__tui_9 := tui.New(
		tui.WithText("3"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_9)
	if a.fmTab.Get() == 2 {
		__tui_10 := tui.New(
			tui.WithText("Plugins/Mods"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_10)
	} else {
		__tui_11 := tui.New(
			tui.WithText("Plugins/Mods"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_11)
	}
	__tui_0.AddChild(__tui_2)
	if len(a.fmItems()) == 0 {
		__tui_12 := tui.New(
			tui.WithText("(empty)"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_12)
	}
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, a.fmScrollY()),
	)
	for __idx_0, item := range a.fmItems() {
		_ = __idx_0
		if item.Sel {
			__tui_14 := tui.New(
				tui.WithText(fmt.Sprintf("> %s", item.Text)),
				tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
			)
			__tui_13.AddChild(__tui_14)
		} else {
			__tui_15 := tui.New(
				tui.WithText(fmt.Sprintf("  %s", item.Text)),
			)
			__tui_13.AddChild(__tui_15)
		}
	}
	__tui_0.AddChild(__tui_13)
	if a.fmEditing.Get() {
		__tui_16 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_17 := tui.New(
			tui.WithText(fmt.Sprintf("%s =", a.fmSelectedKey())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_16.AddChild(__tui_17)
		__tui_18 := tui.New(
			tui.WithText(a.fmEditText.Get()),
		)
		__tui_16.AddChild(__tui_18)
		__tui_19 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_16.AddChild(__tui_19)
		__tui_20 := tui.New(
			tui.WithText("(Enter applies | Esc cancels)"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_16.AddChild(__tui_20)
		__tui_0.AddChild(__tui_16)
	}
	if a.fmConfirm.Get() != "" {
		__tui_21 := tui.New(
			tui.WithText(fmt.Sprintf("Delete %q permanently? (y = yes, n = no)", a.fmConfirm.Get())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_0.AddChild(__tui_21)
	}
	if a.fmMsg.Get() != "" {
		__tui_22 := tui.New(
			tui.WithText(a.fmMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_22)
	}
	__tui_23 := HintsRow(a.fmHints(), false)
	__tui_0.AddChild(__tui_23.Root)

	watchers = append(watchers, __tui_23.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_23).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_23).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = FilesViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
