// Code generated by tui generate. DO NOT EDIT.
// Source: help_view.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type HelpViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *HelpViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *HelpViewView) GetRoot() *tui.Element { return v.Root }

func (v *HelpViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *HelpViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *HelpViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *HelpViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*HelpViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*HelpViewView)(nil)

var _ tui.AppUnbinder = (*HelpViewView)(nil)

var _ tui.PropsUpdater = (*HelpViewView)(nil)

func HelpView(a *app) *HelpViewView {
	var view HelpViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, 0),
	)
	__tui_1 := tui.New(
		tui.WithText("Keyboard shortcuts"),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	for __idx_0, sec := range helpSections {
		_ = __idx_0
		__tui_2 := tui.New(
			tui.WithText(sec.Title),
			tui.WithFlexShrink(0),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_0.AddChild(__tui_2)
		for __idx_1, k := range sec.Keys {
			_ = __idx_1
			__tui_3 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			__tui_4 := tui.New(
				tui.WithText(k.K),
				tui.WithMinWidth(16),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_3.AddChild(__tui_4)
			__tui_5 := tui.New(
				tui.WithText(k.L),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_3.AddChild(__tui_5)
			__tui_0.AddChild(__tui_3)
		}
	}
	__tui_6 := tui.New(
		tui.WithText("Press Esc or ? to close"),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_6)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = HelpViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
