// Code generated by tui generate. DO NOT EDIT.
// Source: modrinth_view.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type ModrinthViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ModrinthViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ModrinthViewView) GetRoot() *tui.Element { return v.Root }

func (v *ModrinthViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ModrinthViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ModrinthViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ModrinthViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ModrinthViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ModrinthViewView)(nil)

var _ tui.AppUnbinder = (*ModrinthViewView)(nil)

var _ tui.PropsUpdater = (*ModrinthViewView)(nil)

func ModrinthView(a *app) *ModrinthViewView {
	var view ModrinthViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Green)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText(fmt.Sprintf("Modrinth %s — %s", a.mrKind.Get(), a.currentName())),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Green)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_3 := tui.New(
		tui.WithText("Search:"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(a.mrQuery.Get()),
	)
	__tui_2.AddChild(__tui_4)
	if a.mrTyping.Get() {
		__tui_5 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Blink()),
		)
		__tui_2.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_2)
	__tui_6 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, scrollTo(a.mrIdx.Get())),
	)
	for __idx_0, item := range a.mrItems() {
		_ = __idx_0
		if item.Sel {
			__tui_7 := tui.New(
				tui.WithText(fmt.Sprintf("> %s", item.Text)),
				tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Green)),
			)
			__tui_6.AddChild(__tui_7)
		} else {
			__tui_8 := tui.New(
				tui.WithText(fmt.Sprintf("  %s", item.Text)),
			)
			__tui_6.AddChild(__tui_8)
		}
	}
	__tui_0.AddChild(__tui_6)
	if a.mrMsg.Get() != "" {
		__tui_9 := tui.New(
			tui.WithText(a.mrMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_9)
	}
	__tui_10 := HintsRow(a.mrHints(), true)
	__tui_0.AddChild(__tui_10.Root)

	watchers = append(watchers, __tui_10.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_10).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_10).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = ModrinthViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
