// Code generated by tui generate. DO NOT EDIT.
// Source: players_view.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type PlayersViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *PlayersViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *PlayersViewView) GetRoot() *tui.Element { return v.Root }

func (v *PlayersViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *PlayersViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *PlayersViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *PlayersViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*PlayersViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*PlayersViewView)(nil)

var _ tui.AppUnbinder = (*PlayersViewView)(nil)

var _ tui.PropsUpdater = (*PlayersViewView)(nil)

func PlayersView(a *app) *PlayersViewView {
	var view PlayersViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText(fmt.Sprintf("Players — %s · %s", a.currentName(), plTabsInfo[a.plTab.Get()].Title)),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_3 := tui.New(
		tui.WithText("1"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_3)
	if a.plTab.Get() == 0 {
		__tui_4 := tui.New(
			tui.WithText("Whitelist"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_4)
	} else {
		__tui_5 := tui.New(
			tui.WithText("Whitelist"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_5)
	}
	__tui_6 := tui.New(
		tui.WithText("2"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_6)
	if a.plTab.Get() == 1 {
		__tui_7 := tui.New(
			tui.WithText("Ops"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_7)
	} else {
		__tui_8 := tui.New(
			tui.WithText("Ops"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_8)
	}
	__tui_9 := tui.New(
		tui.WithText("3"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_9)
	if a.plTab.Get() == 2 {
		__tui_10 := tui.New(
			tui.WithText("Banned"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2.AddChild(__tui_10)
	} else {
		__tui_11 := tui.New(
			tui.WithText("Banned"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_2.AddChild(__tui_11)
	}
	__tui_0.AddChild(__tui_2)
	if len(a.plItems()) == 0 {
		__tui_12 := tui.New(
			tui.WithText("(empty)"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_12)
	}
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, scrollTo(a.plIdx.Get())),
	)
	for __idx_0, item := range a.plItems() {
		_ = __idx_0
		if item.Sel {
			__tui_14 := tui.New(
				tui.WithText(fmt.Sprintf("> %s", item.Text)),
				tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
			)
			__tui_13.AddChild(__tui_14)
		} else {
			__tui_15 := tui.New(
				tui.WithText(fmt.Sprintf("  %s", item.Text)),
			)
			__tui_13.AddChild(__tui_15)
		}
	}
	__tui_0.AddChild(__tui_13)
	if a.plAdding.Get() {
		__tui_16 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_17 := tui.New(
			tui.WithText("Player name:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_16.AddChild(__tui_17)
		__tui_18 := tui.New(
			tui.WithText(a.plText.Get()),
		)
		__tui_16.AddChild(__tui_18)
		__tui_19 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_16.AddChild(__tui_19)
		__tui_0.AddChild(__tui_16)
	}
	if a.plMsg.Get() != "" {
		__tui_20 := tui.New(
			tui.WithText(a.plMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_20)
	}
	__tui_21 := HintsRow(a.plHints(), false)
	__tui_0.AddChild(__tui_21.Root)

	watchers = append(watchers, __tui_21.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_21).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_21).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = PlayersViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
