// Code generated by tui generate. DO NOT EDIT.
// Source: splash_view.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type SplashViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SplashViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SplashViewView) GetRoot() *tui.Element { return v.Root }

func (v *SplashViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SplashViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SplashViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SplashViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SplashViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SplashViewView)(nil)

var _ tui.AppUnbinder = (*SplashViewView)(nil)

var _ tui.PropsUpdater = (*SplashViewView)(nil)

func SplashView(a *app) *SplashViewView {
	var view SplashViewView
	var watchers []tui.Watcher

	var __tui_0 *tui.Element
	if a.splashCompact() {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithHeightPercent(100.00),
			tui.WithAlign(tui.AlignCenter),
			tui.WithJustify(tui.JustifyCenter),
			tui.WithGap(1),
		)
		__tui_2 := tui.New(
			tui.WithText("MC-TUI SERVER"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.RGBColor(124, 198, 92))),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("Press any key to start"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_3)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithHeightPercent(100.00),
			tui.WithAlign(tui.AlignCenter),
			tui.WithJustify(tui.JustifyCenter),
			tui.WithGap(1),
		)
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		for __idx_0, row := range splashLogoRows() {
			_ = __idx_0
			__tui_6 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			)
			for __idx_1, seg := range row {
				_ = __idx_1
				if seg.Key == "g" {
					__tui_7 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(124, 198, 92))),
					)
					__tui_6.AddChild(__tui_7)
				} else if seg.Key == "G" {
					__tui_8 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(74, 158, 49))),
					)
					__tui_6.AddChild(__tui_8)
				} else if seg.Key == "d" {
					__tui_9 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(92, 61, 36))),
					)
					__tui_6.AddChild(__tui_9)
				} else if seg.Key == "b" {
					__tui_10 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(139, 98, 68))),
					)
					__tui_6.AddChild(__tui_10)
				} else if seg.Key == "t" {
					__tui_11 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(160, 118, 76))),
					)
					__tui_6.AddChild(__tui_11)
				} else {
					__tui_12 := tui.New(
						tui.WithText(seg.Text),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(154, 143, 138))),
					)
					__tui_6.AddChild(__tui_12)
				}
			}
			__tui_5.AddChild(__tui_6)
		}
		__tui_4.AddChild(__tui_5)
		__tui_13 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		for __idx_0, line := range splashTitle {
			_ = __idx_0
			__tui_14 := tui.New(
				tui.WithText(line),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.RGBColor(124, 198, 92))),
			)
			__tui_13.AddChild(__tui_14)
		}
		__tui_4.AddChild(__tui_13)
		__tui_15 := tui.New(
			tui.WithText("Press any key to start"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_4.AddChild(__tui_15)
		if __tui_0 == nil {
			__tui_0 = __tui_4
		}
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SplashViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
