// Code generated by tui generate. DO NOT EDIT.
// Source: wizard_view.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type WizardViewView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *WizardViewView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *WizardViewView) GetRoot() *tui.Element { return v.Root }

func (v *WizardViewView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *WizardViewView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *WizardViewView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *WizardViewView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*WizardViewView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*WizardViewView)(nil)

var _ tui.AppUnbinder = (*WizardViewView)(nil)

var _ tui.PropsUpdater = (*WizardViewView)(nil)

func WizardView(a *app) *WizardViewView {
	var view WizardViewView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_1 := tui.New(
		tui.WithText(fmt.Sprintf("New instance — %s", a.wizStepTitle())),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	if a.wizStep.Get() == wizType {
		for __idx_0, item := range a.wizTypeItems() {
			_ = __idx_0
			if item.Sel {
				__tui_2 := tui.New(
					tui.WithText(fmt.Sprintf("> %s", item.Text)),
					tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
				)
				__tui_0.AddChild(__tui_2)
			} else {
				__tui_3 := tui.New(
					tui.WithText(fmt.Sprintf("  %s", item.Text)),
				)
				__tui_0.AddChild(__tui_3)
			}
		}
	}
	if a.wizStep.Get() == wizLoading {
		__tui_4 := tui.New(
			tui.WithText(a.wizMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_4)
	}
	if a.wizStep.Get() == wizVersion {
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexGrow(1),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, scrollTo(a.wizVerIdx.Get())),
		)
		for __idx_0, item := range a.wizVersionItems() {
			_ = __idx_0
			if item.Sel {
				__tui_6 := tui.New(
					tui.WithText(fmt.Sprintf("> %s", item.Text)),
					tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
				)
				__tui_5.AddChild(__tui_6)
			} else {
				__tui_7 := tui.New(
					tui.WithText(fmt.Sprintf("  %s", item.Text)),
				)
				__tui_5.AddChild(__tui_7)
			}
		}
		__tui_0.AddChild(__tui_5)
	}
	if a.wizStep.Get() == wizPackSearch {
		__tui_8 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_9 := tui.New(
			tui.WithText("Search modpacks:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_8.AddChild(__tui_9)
		__tui_10 := tui.New(
			tui.WithText(a.wizPackQuery.Get()),
		)
		__tui_8.AddChild(__tui_10)
		__tui_11 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_8.AddChild(__tui_11)
		__tui_0.AddChild(__tui_8)
		__tui_12 := tui.New(
			tui.WithText("Server-side modpacks: Fabric, Forge, NeoForge and Quilt"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_12)
		if a.wizMsg.Get() != "" {
			__tui_13 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_0.AddChild(__tui_13)
		}
	}
	if a.wizStep.Get() == wizPackList {
		__tui_14 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexGrow(1),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, scrollTo(a.wizPackIdx.Get())),
		)
		for __idx_0, item := range a.wizPackItems() {
			_ = __idx_0
			if item.Sel {
				__tui_15 := tui.New(
					tui.WithText(fmt.Sprintf("> %s", item.Text)),
					tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
				)
				__tui_14.AddChild(__tui_15)
			} else {
				__tui_16 := tui.New(
					tui.WithText(fmt.Sprintf("  %s", item.Text)),
				)
				__tui_14.AddChild(__tui_16)
			}
		}
		__tui_0.AddChild(__tui_14)
	}
	if a.wizStep.Get() == wizPackVer {
		__tui_17 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexGrow(1),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, scrollTo(a.wizPackVerIdx.Get())),
		)
		for __idx_0, item := range a.wizPackVerItems() {
			_ = __idx_0
			if item.Sel {
				__tui_18 := tui.New(
					tui.WithText(fmt.Sprintf("> %s", item.Text)),
					tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
				)
				__tui_17.AddChild(__tui_18)
			} else {
				__tui_19 := tui.New(
					tui.WithText(fmt.Sprintf("  %s", item.Text)),
				)
				__tui_17.AddChild(__tui_19)
			}
		}
		__tui_0.AddChild(__tui_17)
	}
	if a.wizStep.Get() == wizImpPath {
		__tui_20 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_21 := tui.New(
			tui.WithText("Folder:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_20.AddChild(__tui_21)
		__tui_22 := tui.New(
			tui.WithText(a.wizImpPath.Get()),
		)
		__tui_20.AddChild(__tui_22)
		__tui_23 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_20.AddChild(__tui_23)
		__tui_0.AddChild(__tui_20)
		__tui_24 := tui.New(
			tui.WithText("Full path of an existing server folder — files are not moved"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_24)
		if a.wizMsg.Get() != "" {
			__tui_25 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_0.AddChild(__tui_25)
		}
	}
	if a.wizStep.Get() == wizImpVer {
		__tui_26 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_27 := tui.New(
			tui.WithText("Minecraft version (optional):"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_26.AddChild(__tui_27)
		__tui_28 := tui.New(
			tui.WithText(a.wizImpVer.Get()),
		)
		__tui_26.AddChild(__tui_28)
		__tui_29 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_26.AddChild(__tui_29)
		__tui_0.AddChild(__tui_26)
		__tui_30 := tui.New(
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_31 := tui.New(tui.WithText("Used to filter Modrinth content; leave empty"))
		__tui_30.AddChild(__tui_31)
		__tui_32 := tui.New(tui.WithText("unsure"))
		__tui_30.AddChild(__tui_32)
		__tui_0.AddChild(__tui_30)
	}
	if a.wizStep.Get() == wizName {
		__tui_33 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_34 := tui.New(
			tui.WithText("Name:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_33.AddChild(__tui_34)
		__tui_35 := tui.New(
			tui.WithText(a.wizName.Get()),
		)
		__tui_33.AddChild(__tui_35)
		__tui_36 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_33.AddChild(__tui_36)
		__tui_0.AddChild(__tui_33)
		if a.wizMsg.Get() != "" {
			__tui_37 := tui.New(
				tui.WithText(a.wizMsg.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_0.AddChild(__tui_37)
		}
	}
	if a.wizStep.Get() == wizMem {
		__tui_38 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_39 := tui.New(
			tui.WithText("Memory (MB):"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_38.AddChild(__tui_39)
		__tui_40 := tui.New(
			tui.WithText(a.wizMemory.Get()),
		)
		__tui_38.AddChild(__tui_40)
		__tui_41 := tui.New(
			tui.WithText("_"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Blink()),
		)
		__tui_38.AddChild(__tui_41)
		__tui_0.AddChild(__tui_38)
	}
	if a.wizStep.Get() == wizEula {
		__tui_42 := tui.New(
			tui.WithText("To run the server you must accept the Minecraft EULA:"),
		)
		__tui_0.AddChild(__tui_42)
		__tui_43 := tui.New(
			tui.WithText("https://aka.ms/MinecraftEULA"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_0.AddChild(__tui_43)
		__tui_44 := tui.New(
			tui.WithText("Do you accept?"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_0.AddChild(__tui_44)
	}
	if a.wizStep.Get() == wizDownload {
		__tui_45 := tui.New(
			tui.WithText(a.wizMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_45)
	}
	if a.wizStep.Get() == wizError {
		__tui_46 := tui.New(
			tui.WithText(a.wizMsg.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_0.AddChild(__tui_46)
	}
	__tui_47 := HintsRow(a.wizHints(), false)
	__tui_0.AddChild(__tui_47.Root)

	watchers = append(watchers, __tui_47.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_47).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_47).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = WizardViewView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
